Tuesday September 24th 2013 12:37 pm -04:00,Hi Im receiving this errorTraceback (most recent call last):  File ...\a3_driver.py line 88 in <module>    words = a3.read_words(words_file)  File ...\a3.py line 185 in read_words    words = open(words_file r)TypeError: invalid file: <_io.TextIOWrapper name=.../wordlist1.txt mode=r encoding=cp1252>selecting the given word list file wordlist1.txt which is placed in the same directory of the main program.The function read_words in a3.py is the following one:def read_words(words_file):     (file open for reading) -> list of str    Return a list of all words (with newlines removed) from open file    words_file.    Precondition: Each line of the file contains a word in uppercase characters    from the standard English alphabet.        words = open(words_file r)    allwords = words.readlines()    wordlist =         for word in allwords:        wordlist.append(word.rstrip())            return wordlistThis is working calling the function in this way:read_words(wordlist1.txt)and it is returning the words list[CRUNCHY COWS EAT GRASS]Is there anything I missed?Thanks in advance for your help!, Resolved,0
Wednesday September 25th 2013 4:13 am -04:00,...and now its working!Thank you so much! Ill read the contract carefully in the future! :-), Resolved,0
