Monday September 2nd 2013 3:50 pm -04:00,GerritThank you for the explanation it was the trigger that made me realize what I was doing wrong. Since I was calling functions I put the arguments where the parameters belong forgetting the fact I was calling functions within a function where the arguments are supplied by the parameter (word in this case from the count_letters(word) function) in stead of arguments directly. Thank youRick, Unresolved,0
Monday September 2nd 2013 5:59 pm -04:00,NancyThe functions are not specifically defined except the question states they are. You just need to call them as if they were defined. If you were actually programming this with IDLE they would need to be defined.  See if this will help. Follow this through starting from word_count = count_letters(hello) at the bottom and see if it will help. If you were to program this this is how the functions count_vowels and count_consonants would need to be defined. if you find syntax errors which there could be dont worry about them just follow the logic.def count_vowles(vowl_word):    (str) -> number               body of function to count vowles         return number_of_vowles    def count_consonants(cons_word):     (str) -> number               body of function to count consonants        return number_of_consonants    def count_letters(word):         (str) -> int    Return the number of letters in word.    >>> count_letters(hello)    5    >>> count_letters(bonjour)    7        return (place here the body of function that calls count_vowles and count_consonants)word_count = count_letters(hello)Tell us your thoughts and we can guide you from there.Good luck, Unresolved,2
Monday September 2nd 2013 6:20 pm -04:00,Youre welcome. I took me a while to figure out what I was doing wrong., Unresolved,0
Friday October 4th 2013 1:20 am -04:00,I am having the same problem now. I submitted my results yesterday after completing every function except the last two and got a Success on all the completed ones but now after completing all the functions I am getting errors on all functions. I checked the location of my a3.py file and it is correct. I even tried renaming the file to a3_copy.py and the autograder still gave me all errors.If the last two functions are incorrect which worked when running them in IDLE would it affect the earlier functions? When the functions were incomplete I had no problems.Is anyone having this problem at this time?I found my problem. I used the import command to import askopenfile function to test out its functionality but forgot to remove it before submitting my last results. It is working properly now after removing it. , Unresolved,0
Friday October 4th 2013 2:20 am -04:00,Thank you Tom your string to list function did the trick that was all I lacked. , Resolved,0
